In [19]:
import numpy as np
x=np.random.randint(1,100,[150,4])
def fun(a):
    return np.mean(a)
mean=np.apply_along_axis(fun,0,x)
x_u=x-mean
x_u_t=np.transpose(x_u)
shape=x.shape[0]
cov=(np.matmul(x_u_t,x_u))/shape
print(cov)


[[ 867.45995556 -152.6616      -51.91964444   59.70431111]
 [-152.6616      696.6624     -104.57386667   31.00186667]
 [ -51.91964444 -104.57386667  804.87715556   18.15217778]
 [  59.70431111   31.00186667   18.15217778  753.21515556]]
